name: Build Release Android Library

on:
  workflow_dispatch:

jobs:
  build-dev:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Build the App with Type - Release
        env:
          STORE_PASS: ${{ secrets.STORE_PASS }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASS: ${{ secrets.KEY_PASS }}
        run: |
          BUILD_COMMAND="./gradlew clean assembleRelease"

          echo "Building with command: $BUILD_COMMAND"
          $BUILD_COMMAND

      - name: Copy AAR and POM artifacts
        run: |
          ./gradlew :analytics:copyAARRelease
          ./gradlew :appsflyer_analytics:copyAARRelease
          ./gradlew :firebase_analytics:copyAARRelease
          ./gradlew :yandex_metrica_analytics:copyAARRelease

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aar-artifacts
          path: artifacts/release