name: Build and Publish Android Library

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: 'Build Type (Debug or Release)'
        required: true
        type: choice
        options:
          - Debug
          - Release
  push:
    branches:
      - '*'

jobs:
  build-dev:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Build the Library
        run: |
          BUILD_TYPE=${{ github.event.inputs.buildType }}
          BUILD_COMMAND="./gradlew clean assemble${BUILD_TYPE}"

          echo "Building with command: $BUILD_COMMAND"
          $BUILD_COMMAND

      - name: Copy AAR and POM artifacts
        run: |
          ./gradlew :analytics:copyAARDebug

      - name: Upload AAR Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aar-artifacts
          path: |
            analytics/build/outputs/aar/*.aar

  publish-dev:
    needs: build-dev
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download AAR and POM artifacts
        uses: actions/download-artifact@v4
        with:
          name: aar-artifacts
          path: artifacts

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Publish to GitHub Packages
        env:
          PACKAGE_UPLOAD_USER: ${{ github.actor }}
          PACKAGE_UPLOAD_PASSWORD: ${{ secrets.PACKAGE_TOKEN }}
        run: |
          BUILD_TYPE=${{ github.event.inputs.buildType }}
          BUILD_COMMAND="./gradlew publish"

          echo "Building with command: $BUILD_COMMAND"
          $BUILD_COMMAND
