name: Build and Publish Android Library

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: 'Build Type (Debug or Release)'
        required: true
        type: choice
        options:
          - Debug
          - Release
  push:
    branches:
      - '*'

jobs:
  build-dev:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Build the Library
        env:
          STORE_PASS: ${{ secrets.STORE_PASS }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASS: ${{ secrets.KEY_PASS }}
        run: |
          BUILD_TYPE=${{ github.event.inputs.buildType }}
          BUILD_COMMAND="./gradlew clean assemble${BUILD_TYPE}"

          echo "Building with command: $BUILD_COMMAND"
          $BUILD_COMMAND

      - name: Copy AAR and POM artifacts
        run: |
          ./gradlew :analytics:copyAARDebug

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aar-artifacts
          path: artifacts/${{ github.event.inputs.build_type }}

  publish-dev:
    needs: build-dev
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Download AAR and POM artifacts
        uses: actions/download-artifact@v4
        with:
          name: aar-artifacts
          path: artifacts/

      - name: Display AAR Debug  - structure of downloaded files
        run: ls -R
        working-directory: artifacts/

      - name: Publish to GitHub Packages
        env:
          PACKAGE_UPLOAD_USER: ${{ github.actor }}
          PACKAGE_UPLOAD_PASSWORD: ${{ secrets.PACKAGE_TOKEN }}
        run: |
          BUILD_COMMAND="./gradlew publish"

          echo "Building with command: $BUILD_COMMAND"
          $BUILD_COMMAND
