name: Publish Release Android Library

on:
  workflow_run:
    workflows: ["Build Release Android Library"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Download AAR and POM artifacts
        uses: actions/download-artifact@v4
        with:
          name: aar-artifacts
          path: artifacts/

      - name: Display AAR  - structure of downloaded files
        run: ls -R
        working-directory: artifacts/

      - name: Publish to GitHub Packages
        env:
          PACKAGE_UPLOAD_USER: ${{ github.actor }}
          PACKAGE_UPLOAD_PASSWORD: ${{ secrets.PACKAGE_TOKEN }}
        run: |
          BUILD_COMMAND="./gradlew publish"

          echo "Building with command: $BUILD_COMMAND"
          $BUILD_COMMAND
